empiricaly/empirica

imports/core/api/games/create.js, imports/core/api/players/methods.js, imports/core/lib/utils.js, imports/core/startup/server/index.js
This should improve assignments dramatically. But it's hard to test. I tested a bit locally, but it definitely needs more testing. And I created a PR so that we can do a code review first, see if there's anything visibly wrong with the changes. See #57 for details.
=> Assignment adjustments

imports/core/api/players/methods.js, imports/core/api/players/players.js, imports/core/api/players/server/publications.js, imports/core/ui/components/Login.jsx, imports/core/ui/components/NewPlayer.jsx, imports/core/ui/components/Toasters.jsx, imports/core/ui/components/admin/AdminCondition.jsx, imports/core/ui/components/admin/AdminNewBatch.jsx, imports/core/ui/components/admin/AdminNewCondition.jsx, imports/core/ui/components/admin/AdminNewLobbyConfig.jsx, imports/core/ui/components/admin/AdminNewTreatment.jsx, imports/core/ui/components/admin/AdminPlayers.jsx, imports/core/ui/containers/IdentifiedRoute.jsx, imports/experiment/client/intro/Quiz.jsx
This is the second half the #57 fix assignment ticket, adding a button to clear players.
=> Add Admin button to clear players with gameFull exit Status

internal/templates/source/react/src/examples/JellyBeans.jsx
=> feat: enhance result stage of jellybeans

e2e-tests/page-objects/admin/BatchesAdminPage.ts, e2e-tests/tests/multiplayer-two-players.spec.ts, e2e-tests/tests/players-assigments.spec.ts, e2e-tests/tests/players-kicked-out.spec.ts
Extended Batches page object
Added the following tests scenarios:
1. create a simple batch with 2 games for solo players, 2 players are assigned to two games
2. create a simple batch with 2 games for solo players, stop batch, players get kicked out
=> Implement a few e2e tests for assigments

e2e-tests/package.json, e2e-tests/tests/players-assignments-performance.spec.ts
- All players are created at once
- Testing with 10 concurrent is currently mostly stable
=> Implement basic performance test to check assignments

.changeset/smart-sheep-shave.md, lib/@empirica/core/src/player/classic/react/hooks.ts
=> Fix timer not showing when player joins a game

.changeset/polite-taxis-relax.md, package-lock.json, package.json
Once the PR is released, there will be a major (v.3.0.0) release of the chat package.
Still in draft due to missing feature in the Core
=> Add release info for the chat component

.changeset/hungry-guests-compare.md, lib/admin-ui/README.md, lib/admin-ui/src/components/batches/BatchLine.svelte, lib/admin-ui/vite.config.js
- Implements https://github.com/empiricaly/empirica/issues/243
- Added docs on dev env for the admin UI
- Added proxy configuration for an existing empirica project to use the dev admin UI
=> Display custom batch json in admin page

.changeset/large-games-learn.md, lib/@empirica/core/src/admin/classic/classic.ts, lib/admin-ui/src/components/games/GameLine.svelte, lib/admin-ui/src/components/games/GamesLine.svelte, lib/admin-ui/src/components/players/Players.svelte, lib/admin-ui/src/main.js
- Implement stage submission with player dropout (#219)
- Fix error console when receieving the ParticipantConnected/Participant disconnected event
- Fix issue with a player being displayed as ready despite being offline. A disconnected player will be displayed consistently to the player page:
=> Implement stage submission with player dropout (#219). And bug fixes

.changeset/hungry-poems-crash.md, .github/workflows/release_package.yml, build/Dockerfile
Also, added a fake changeset to verify that the build has worked
=> Add condition to build only x64 for linux for the first step in the CI

.changeset/mean-moles-press.md, internal/templates/source/callbacks/src/index.js, lib/@empirica/core/src/admin/classic/classic.ts
Resolves https://github.com/empiricaly/empirica/issues/213.
Also, updated the template to make it explicitly shown by default.
=> Add option to disable the batch autoend

.changeset/friendly-garlics-poke.md, .gitpod.yml, internal/callbacks/callbacks.go, internal/templates/source/callbacks/package.json, internal/term/term.go
=> fix: show callback errors

.changeset/README.md, .changeset/fix-intro-reload.md, lib/@empirica/core/src/player/classic/react/Steps.tsx
fixes #263
@JamesPHoughton This should fix your issue. Took me a while to get to fully testing this, my apologies.
=> fix: intro hard reload

.changeset/publish-assigned-game.md, .github/workflows/build_and_release.yaml, lib/@empirica/core/src/admin/classic/models.ts
=> fix: publish game when assigned

.changeset/intro-wait-for-game.md, .changeset/show-lobby-unstarted-game.md, lib/@empirica/core/src/player/classic/react/EmpiricaContext.tsx
=> fix: pre-game-fixes

.changeset/admin-buttons.md, .changeset/menu-positions.md, .changeset/reliable-subprocs.md, cmds/empirica/cmd/export.go, cmds/proxy/cmd/root.go, internal/bundle/serve.go, internal/callbacks/callbacks.go, internal/experiment/utils.go, internal/player/player.go, internal/settings/shared.go, lib/@empirica/core/src/player/react/EmpiricaMenu.tsx, lib/admin-ui/src/style.css, lib/admin-ui/uno.config.ts
Reverts empiricaly/empirica#353
=> Revert "fix: various fixes"

.changeset/fix-attr-set-false.md, lib/@empirica/core/src/shared/attributes.ts, tests/stress/experiment/server/src/callbacks.js, tests/stress/tests/attributes.spec.js, tests/stress/tests/player.js
=> fix: attr to false on server

.changeset/add-ephemeral-attributes.md, .changeset/game-ended-ready.md, .changeset/player-reset-admin.md, lib/@empirica/core/CHANGELOG.md, lib/@empirica/core/package.json
Reverts empiricaly/empirica#535
=> Revert "Version Packages"

.changeset/export-from-file.md, .gitignore, cmds/empirica/cmd/export.go
=> feat: export from tajriba.json file

.changeset/export-null-attribute.md, go.mod, go.sum, internal/export/export.go
=> fix: export null attributes

.changeset/extra-mkdir.md, internal/callbacks/callbacks.go, internal/templates/templates.go
=> fix: extra mkdir

.changeset/assignment-alternatives.md, lib/@empirica/core/src/admin/classic/classic.ts, tests/stress/experiment/server/src/index.js, tests/stress/tests/admin.js, tests/stress/tests/assignment.spec.js
=> feat: add assignment alternatives

.changeset/lobby-game-ended.md, lib/@empirica/core/src/admin/classic/classic.ts, lib/@empirica/core/src/admin/classic/models.ts
=> fix: assignment to prematurely ended games
